bind b set-window-option synchronize-panes\; display-message "synchronize mode toggled."

set -g mouse on

# option arrow keys to switch panes
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D

# easy window split
bind-key v split-window -h
bind-key h split-window -v

# shift arrow switch windows
bind -n S-Left previous-window
bind -n S-Right next-window
